steps:

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['rsync', 'gs://${_CONFIG_BUCKET}/${_CONFIG_PROJECT}', '/config']
    volumes:
    - name: 'config'
      path: '/config'

  - name: 'gcr.io/$PROJECT_ID/ci-buildnum'
    args: ['/config/buildnum', '/config/.buildenv', '/config/$BUILD_ID.json']
    volumes:
    - name: 'config'
      path: '/config'

  - name: 'gcr.io/$PROJECT_ID/ci-build-deployment-logger'
    args: ['/config']
    env: 
    - 'REPO_NAME=$REPO_NAME'
    - 'BRANCH_NAME=$BRANCH_NAME'
    - '_UCD_LIB_INITIATOR=$_UCD_LIB_INITIATOR'
    - '_GITHUB_EVENT=$_GITHUB_EVENT'
    - '_GITHUB_ISSUE_NUMBER=$_GITHUB_ISSUE_NUMBER'
    - '_GITHUB_REPOSITORY=$_GITHUB_REPOSITORY'
    - '_GITHUB_PR_USER=$_GITHUB_PR_USER'
    - '_GITHUB_PR_MERGED_BY=$_GITHUB_PR_MERGED_BY'
    - 'BUILD_ID=$BUILD_ID'
    volumes:
    - name: 'config'
      path: '/config'

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '/config/buildnum', 'gs://${_CONFIG_BUCKET}/${_CONFIG_PROJECT}/buildnum']
    volumes:
    - name: 'config'
      path: '/config'

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', '/config/${BUILD_ID}', 'gs://${_CONFIG_BUCKET}/${_CONFIG_PROJECT}/${BUILD_ID}']
    volumes:
    - name: 'config'
      path: '/config'

  - name: node:14
    entrypoint: "npm"
    args: ["install"]

  - name: node:14
    entrypoint: "bash"
    args: ["-c", "cd elements/brand; npm install" ]

  - name: buildkite/puppeteer:10.0.0
    entrypoint: "npm"
    args: ["run", "test" ]
    env:
      - 'PUPPETEER_SANDBOX=true'

  - name: node:14
    entrypoint: "bash"
    args: ["-c", "cd test-app; npm install" ]

  - name: node:14
    entrypoint: "bash"
    args: ["-c", "cd test-app; npm run dist" ]

  - name: gcr.io/cloud-builders/docker
    entrypoint: "docker"
    args: ["pull", "gcr.io/ucdlib-pubreg/ucdlib-theme-demo"]

  - name: gcr.io/cloud-builders/docker
    entrypoint: "docker"
    args: ["build", "test-app", "-t", "gcr.io/ucdlib-pubreg/ucdlib-theme-demo"]

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: "gcloud"
    args: ["beta", "run", "deploy", "ucdlib-theme-demo", 
      "--image=gcr.io/ucdlib-pubreg/ucdlib-theme-demo",
      "--platform=managed",
      "--memory=1Gi",
      "--region=us-central1"
    ]
    env: 
      - 'REPO_NAME=$REPO_NAME'
      - 'BRANCH_NAME=$BRANCH_NAME'
      - 'SHORT_SHA=$SHORT_SHA'
      - 'TAG_NAME=$TAG_NAME'
      - '_UCD_LIB_INITIATOR=$_UCD_LIB_INITIATOR'
      - '_GITHUB_EVENT=$_GITHUB_EVENT'
      - '_GITHUB_ISSUE_NUMBER=$_GITHUB_ISSUE_NUMBER'
      - '_GITHUB_REPOSITORY=$_GITHUB_REPOSITORY'
      - '_GITHUB_PR_USER=$_GITHUB_PR_USER'
      - '_GITHUB_PR_MERGED_BY=$_GITHUB_PR_MERGED_BY'


substitutions:
  _CONFIG_BUCKET: ci-build-config
  _CONFIG_PROJECT: ucdlib-theme
  _UCD_LIB_INITIATOR: unknown
  _GITHUB_EVENT: ''
  _GITHUB_ISSUE_NUMBER: ''
  _GITHUB_REPOSITORY: ''
  _GITHUB_PR_USER: ''
  _GITHUB_PR_MERGED_BY: ''

timeout: 1800s